### ISSUE TITLE
Wrong variable declaration?

### ISSUE THREAD

**Issue by MatthiasSure** [danclab/burst_detection#11]
Hello all!

I'm trying to get the Matlab version of the burst detection script to work.
However, when trying to run extract_bursts_single_trial.m, I encounter an error on line 162 "Unrecognised function or variable 'closest_pt'".
I also can't find the introduction of the variable "closest_pt" anywhere in the script. 
When I look at the corresponding Phyton script there is also no variable with the name 'closest_pt'. The variable new_peak_time_idx is used at the corresponding point. If I also use new_peak_time_idx instead of 'closest_pt' in the Matlab script, the burst detection runs without any problems.

Is this exchange correct or is the error somewhere else?

Greetings,
Matthias

**Comment by danclab** [comment]
Nice catch! We don't use the matlab verson much and this variable got renamed at some point.
